name: BackstopJS

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - run: npm install

    - run: npm test

    - name: Upload HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: html_report
        path: backstop_data/html_report

    - name: Upload Report
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: report
        path: backstop_data/*_*t # Very tricky
